name: simple commands task

on:
  push:

jobs:

  commands:
    runs-on: ubuntu-latest

    steps:
      - name: checkout stage
        uses: actions/checkout@v4

      - name: simple command task

        run: |
          docker --version
          git --version
          kubectl version --client
