name: simple commands task

on:
  push:

jobs:

  CHECKOUT:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      
  BUILD:
    runs-on: ubuntu-latest
    needs: CHECKOUT 

    steps:
      - run: echo "running building stage"

      - run: echo "building" > app.txt

      - uses: actions/upload-artifact@v4

        with:
          name: app-file
          path: app.txt

  TEST:
    runs-on: ubuntu-latest
    needs: BUILD

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-file

      - run: cat app.txt




