name: runner info tesst

on:
  workflow_dispatch:

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
      - name: show runner details
        run: |
          uname -a
          nproc
          free -h
          docker --version
